// Code generated by protoc-gen-go.
// source: addressbook.proto
// DO NOT EDIT!

/*
Package addressbook is a generated protocol buffer package.

It is generated from these files:
	addressbook.proto

It has these top-level messages:
	Person
	AddressBook
*/
package addressbook

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Person_EmailKind int32

const (
	Person_SCHOOL Person_EmailKind = 0
	Person_HOME   Person_EmailKind = 1
	Person_WORK   Person_EmailKind = 2
)

var Person_EmailKind_name = map[int32]string{
	0: "SCHOOL",
	1: "HOME",
	2: "WORK",
}
var Person_EmailKind_value = map[string]int32{
	"SCHOOL": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_EmailKind) String() string {
	return proto.EnumName(Person_EmailKind_name, int32(x))
}
func (Person_EmailKind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Person struct {
	Id     int32           `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name   *Person_Name    `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Emails []*Person_Email `protobuf:"bytes,3,rep,name=emails" json:"emails,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetName() *Person_Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Person) GetEmails() []*Person_Email {
	if m != nil {
		return m.Emails
	}
	return nil
}

type Person_Name struct {
	Family   string `protobuf:"bytes,1,opt,name=Family" json:"Family,omitempty"`
	Personal string `protobuf:"bytes,2,opt,name=Personal" json:"Personal,omitempty"`
}

func (m *Person_Name) Reset()                    { *m = Person_Name{} }
func (m *Person_Name) String() string            { return proto.CompactTextString(m) }
func (*Person_Name) ProtoMessage()               {}
func (*Person_Name) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Person_Name) GetFamily() string {
	if m != nil {
		return m.Family
	}
	return ""
}

func (m *Person_Name) GetPersonal() string {
	if m != nil {
		return m.Personal
	}
	return ""
}

type Person_Email struct {
	Kind    Person_EmailKind `protobuf:"varint,1,opt,name=kind,enum=addressbook.Person_EmailKind" json:"kind,omitempty"`
	Address string           `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (m *Person_Email) Reset()                    { *m = Person_Email{} }
func (m *Person_Email) String() string            { return proto.CompactTextString(m) }
func (*Person_Email) ProtoMessage()               {}
func (*Person_Email) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *Person_Email) GetKind() Person_EmailKind {
	if m != nil {
		return m.Kind
	}
	return Person_SCHOOL
}

func (m *Person_Email) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type AddressBook struct {
	People []*Person `protobuf:"bytes,1,rep,name=people" json:"people,omitempty"`
}

func (m *AddressBook) Reset()                    { *m = AddressBook{} }
func (m *AddressBook) String() string            { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()               {}
func (*AddressBook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddressBook) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "addressbook.Person")
	proto.RegisterType((*Person_Name)(nil), "addressbook.Person.Name")
	proto.RegisterType((*Person_Email)(nil), "addressbook.Person.Email")
	proto.RegisterType((*AddressBook)(nil), "addressbook.AddressBook")
	proto.RegisterEnum("addressbook.Person_EmailKind", Person_EmailKind_name, Person_EmailKind_value)
}

func init() { proto.RegisterFile("addressbook.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x91, 0x4d, 0x4b, 0xc3, 0x30,
	0x18, 0xc7, 0x6d, 0xd6, 0xc5, 0xed, 0x29, 0x8c, 0xfa, 0x08, 0x12, 0x0b, 0x42, 0xe9, 0xa9, 0x30,
	0x29, 0xac, 0xde, 0x76, 0x53, 0x99, 0x0c, 0xa6, 0x56, 0xa2, 0xe0, 0x39, 0x23, 0x39, 0x84, 0xbe,
	0xa4, 0xb4, 0x5e, 0xfc, 0x66, 0x7e, 0x3c, 0x69, 0x1a, 0xc7, 0x0e, 0xf3, 0x96, 0x7f, 0xf8, 0xfd,
	0x5f, 0x48, 0xe0, 0x42, 0x48, 0xd9, 0xa9, 0xbe, 0xdf, 0x1b, 0x53, 0x66, 0x6d, 0x67, 0xbe, 0x0c,
	0x06, 0x47, 0x57, 0xc9, 0x0f, 0x01, 0xfa, 0xa6, 0xba, 0xde, 0x34, 0xb8, 0x00, 0xa2, 0x25, 0xf3,
	0x62, 0x2f, 0x9d, 0x72, 0xa2, 0x25, 0xde, 0x82, 0xdf, 0x88, 0x5a, 0x31, 0x12, 0x7b, 0x69, 0x90,
	0xb3, 0xec, 0x38, 0x69, 0xb4, 0x64, 0xaf, 0xa2, 0x56, 0xdc, 0x52, 0xb8, 0x02, 0xaa, 0x6a, 0xa1,
	0xab, 0x9e, 0x4d, 0xe2, 0x49, 0x1a, 0xe4, 0xd7, 0xa7, 0xf8, 0xcd, 0x40, 0x70, 0x07, 0x46, 0x6b,
	0xf0, 0x87, 0x00, 0xbc, 0x02, 0xfa, 0x24, 0x6a, 0x5d, 0x7d, 0xdb, 0xf2, 0x39, 0x77, 0x0a, 0x23,
	0x98, 0x8d, 0x3e, 0x51, 0xd9, 0x11, 0x73, 0x7e, 0xd0, 0xd1, 0x07, 0x4c, 0x6d, 0x18, 0xae, 0xc0,
	0x2f, 0x75, 0x33, 0xee, 0x5e, 0xe4, 0x37, 0xff, 0xb6, 0xee, 0x74, 0x23, 0xb9, 0x45, 0x91, 0xc1,
	0xb9, 0xa3, 0x5c, 0xec, 0x9f, 0x4c, 0x96, 0x30, 0x3f, 0xc0, 0x08, 0x40, 0xdf, 0x1f, 0xb7, 0x45,
	0xf1, 0x1c, 0x9e, 0xe1, 0x0c, 0xfc, 0x6d, 0xf1, 0xb2, 0x09, 0xbd, 0xe1, 0xf4, 0x59, 0xf0, 0x5d,
	0x48, 0x92, 0x35, 0x04, 0xf7, 0xa3, 0xef, 0xc1, 0x98, 0x12, 0x97, 0x40, 0x5b, 0x65, 0xda, 0x4a,
	0x31, 0xcf, 0x3e, 0xc0, 0xe5, 0x89, 0x29, 0xdc, 0x21, 0x7b, 0x6a, 0xbf, 0xe2, 0xee, 0x37, 0x00,
	0x00, 0xff, 0xff, 0x6c, 0x9f, 0x21, 0x02, 0x9f, 0x01, 0x00, 0x00,
}
